"""SQLAlchemy ORM models for the pricing schema.

This module defines the three tables that live in the ``pricing`` Postgres
schema.  They back the reinforcement-learning pricing engine used by the
Pricing Service:

* **BanditArm** — stores one Beta-distribution parameter pair per
  (lot, context, multiplier) combination.  The Thompson sampling
  algorithm draws from these distributions to select a price.
* **LotPricingConfig** — per-lot configuration that sets the heuristic
  base price.  The price ceiling used to normalise rewards is derived
  at runtime as ``base_price × max(multipliers)``.
* **PricingEvent** — an append-only log of every price that was offered
  to a user, together with whether the user booked and the resulting
  reward signal fed back to the bandit.

All models use SQLAlchemy 2.0 ``Mapped`` / ``mapped_column`` style and
target a schema called ``pricing`` so they coexist with the inventory
tables inside the same Postgres database.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Optional

from sqlalchemy import (
    Boolean,
    DateTime,
    Float,
    Index,
    Integer,
    Numeric,
    String,
    UniqueConstraint,
)
from sqlalchemy.orm import DeclarativeBase, Mapped, mapped_column


class Base(DeclarativeBase):
    """Shared declarative base for all pricing-schema models."""

    pass


class BanditArm(Base):
    """One arm (price multiplier) in a specific context for a parking lot.

    Each row represents a single *arm* of the contextual multi-armed
    bandit.  An arm is identified by the tuple
    ``(lot_id, context_key, multiplier)``.

    ``context_key`` encodes the discrete context bucket, e.g.
    ``"morning:weekday:high"``.  There are 24 possible context keys
    (4 time-of-day × 2 day-types × 3 occupancy levels).

    ``multiplier`` is applied to the lot's base price to produce the
    final offered price.  Default arms use multipliers in the range
    [0.70 … 1.50].

    The columns ``alpha`` and ``beta`` (mapped as ``beta_param`` in
    Python to avoid shadowing the built-in) are the parameters of a
    Beta distribution.  Thompson sampling draws from
    ``Beta(alpha, beta)`` for every arm in the matching context and
    selects the arm with the highest sample.

    Attributes:
        arm_id:        Auto-incrementing primary key.
        lot_id:        FK-style reference to the parking lot.
        context_key:   Encoded context string, e.g. ``"afternoon:weekend:low"``.
        multiplier:    Price multiplier (e.g. 1.15 means 115 % of base).
        alpha:         Beta-distribution α parameter (starts at 1.0).
        beta_param:    Beta-distribution β parameter (starts at 1.0).
        total_pulls:   Number of times this arm has been selected.
        total_revenue: Cumulative revenue generated by this arm.
        updated_at:    Timestamp of the last parameter update.
    """

    __tablename__ = "bandit_arms"
    __table_args__ = (
        UniqueConstraint("lot_id", "context_key", "multiplier", name="uq_arm_context"),
        {"schema": "pricing"},
    )

    arm_id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    lot_id: Mapped[int] = mapped_column(Integer, nullable=False)
    context_key: Mapped[str] = mapped_column(String(64), nullable=False)
    multiplier: Mapped[float] = mapped_column(Numeric(4, 2), nullable=False)

    # Beta distribution parameters
    alpha: Mapped[float] = mapped_column(Float, nullable=False, default=1.0)
    beta_param: Mapped[float] = mapped_column("beta", Float, nullable=False, default=1.0)

    total_pulls: Mapped[int] = mapped_column(Integer, nullable=False, default=0)
    total_revenue: Mapped[float] = mapped_column(Float, nullable=False, default=0.0)
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )


class LotPricingConfig(Base):
    """Per-lot pricing configuration.

    Stores the *base price* (a heuristic starting rate in $/hr) for a
    parking lot.  The price ceiling used to normalise reward signals
    is derived at runtime as ``base_price × max(multipliers)``.

    Attributes:
        lot_id:        Primary key — matches the lot_id used by the
                       Inventory Service.
        base_price:    Heuristic base price per hour (default $4.00).
        updated_at:    Timestamp of the last configuration change.
    """

    __tablename__ = "lot_pricing_config"
    __table_args__ = {"schema": "pricing"}

    lot_id: Mapped[int] = mapped_column(Integer, primary_key=True)
    base_price: Mapped[float] = mapped_column(
        Numeric(8, 2), nullable=False, default=4.00
    )
    updated_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )


class PricingEvent(Base):
    """Append-only log of pricing decisions and outcomes.

    A new row is inserted by :func:`~pricing.bandit.select_price`
    each time a price is computed for a user.  Initially
    ``booked=False`` and ``reward=0.0``.  When the booking outcome
    is known, :func:`~pricing.bandit.record_booking` or
    :func:`~pricing.bandit.record_no_booking` updates the row
    in-place with the final values.

    This log serves two purposes: it provides an audit trail of
    every pricing decision, and it supplies the historical data
    needed to analyse the bandit's behaviour over time.

    Attributes:
        event_id:      Auto-incrementing primary key.
        lot_id:        The parking lot this price applies to.
        arm_id:        FK to :class:`BanditArm` that was chosen.
        context_key:   The context string at the time of selection.
        base_price:    The lot's base price at the time.
        multiplier:    The multiplier arm that was selected.
        price_offered: ``base_price × multiplier`` — the price shown
                       to the user.
        booked:        Whether the user confirmed a reservation.
        reward:        Normalised revenue: ``price_offered / ceiling``
                       if booked, else ``0.0``.
        created_at:    Timestamp when the outcome was recorded.
    """

    __tablename__ = "pricing_events"
    __table_args__ = (
        Index("idx_pricing_events_lot", "lot_id", "created_at"),
        {"schema": "pricing"},
    )

    event_id: Mapped[int] = mapped_column(Integer, primary_key=True, autoincrement=True)
    lot_id: Mapped[int] = mapped_column(Integer, nullable=False)
    arm_id: Mapped[Optional[int]] = mapped_column(
        Integer, nullable=True
    )
    context_key: Mapped[str] = mapped_column(String(64), nullable=False)
    base_price: Mapped[float] = mapped_column(Numeric(8, 2), nullable=False)
    multiplier: Mapped[float] = mapped_column(Numeric(4, 2), nullable=False)
    price_offered: Mapped[float] = mapped_column(Numeric(8, 2), nullable=False)
    booked: Mapped[bool] = mapped_column(Boolean, nullable=False, default=False)
    reward: Mapped[float] = mapped_column(Float, default=0.0)
    created_at: Mapped[datetime] = mapped_column(
        DateTime(timezone=True),
        default=lambda: datetime.now(timezone.utc),
    )
